### ISSUE TITLE
Question about style block

### ISSUE THREAD

**Issue by ltrottier** [facebookresearch/ResNeXt#1]
Hi,

In appendix "A. Implementation Details: CIFAR" of paper "Aggregated Residual Transformations for Deep Neural Networks", it is written that: "We adopt the pre-activation style block as in [14]", where [14] is the paper "Identity mappings in deep residual networks.". However, when I look at the [resnext_bottleneck_B](https://github.com/facebookresearch/ResNeXt/blob/master/models/resnext.lua#L86), I see it has the original style block with BN before the sum and ReLU after. Did you get your results with the original style block or with the pre-activation style block ?

**Comment by s9xie** [comment]
Hi @ltrottier, thank you for your interest! 
You are totally correct, and the answer is the results are pretty much similar, so we just provided a simpler design. That's why we put a note in the README:

> Note: CIFAR datasets will be automatically downloaded and processed for the first time. Note that in the arXiv paper CIFAR results are based on pre-activated bottleneck blocks and a batch size of 256. We found that better CIFAR test accuracy can be achieved using original bottleneck blocks and a batch size of 128.

**Comment by ltrottier** [comment]
Ok! Thank you for the answer.
